### ISSUE TITLE
Profile / Un-profile loop in appshell2

### ISSUE THREAD

**Issue by noelutz** [PolymerLabs/arcs-cdn#49]
How to reproduce; click on the profile icon several times in a row. The system enters a loop where it automatically selects and unselects the Arc as being a profile Arc.

![share-unshare-loop](https://user-images.githubusercontent.com/6739757/33341310-7506037c-d433-11e7-8d81-ef529845a4e1.gif)

**Comment by sjmiles** [comment]
I believe this is another example of the ping-pong problem that can occur when there are multiple clients (arcs tabs) open and a cycle of notifications is established. So far, fixing these has been a bit of whack-a-mole, which is not really acceptable. Hopefully we can stabilize it by hand, but some kind of automated testing infrastructure is called for soon.

In any case, `remote-visited-arcs` had a bad dirty check that could have caused this (without a repro, it's hard to be sure). This check has been fixed in 51eddfe.

**Comment by smalls** [comment]
I don't see evidence that this still exists (although much has changed so perhaps the issue is still happening but no longer occurring). I'm going to close this.
